// <auto-generated />
namespace SearcherSummary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Resume_Add_PublicationDate_Url : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Resume_Add_PublicationDate_Url));
        
        string IMigrationMetadata.Id
        {
            get { return "201503311741050_Resume_Add_PublicationDate_Url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
