// <auto-generated />
namespace SearcherSummary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Age_int : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Age_int));
        
        string IMigrationMetadata.Id
        {
            get { return "201504041134104_Age_int"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
