// <auto-generated />
namespace SearcherSummary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Experience_not_List : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Experience_not_List));
        
        string IMigrationMetadata.Id
        {
            get { return "201503291536322_Experience_not_List"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
